[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/report-bug.html"
  to = "/report-bug.html"
  status = 200
  force = true

[[redirects]]
  from = "/privacy-policy.html"
  to = "/privacy-policy.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
