"""Output: a CSV to read, and SQL that inserts new rows and enriches existing ones.

The enrich half matters as much as the insert half. BookYourData's 1,163 Metro
Atlanta rows are proven deliverable but carry no title and no proof_url, which
is exactly why the verified-only send filter cannot protect them. Filling those
two fields -- and only where they are currently NULL -- moves that cohort from
"safe on delivery history" to "safe on delivery history and crawl-verified".
"""

from __future__ import annotations

import csv
from pathlib import Path

import _shared  # noqa: F401
import gates_hs
from adapters.base import CoachRecord

CSV_FIELDS = [
    "name", "first_name", "last_name", "title", "school", "state",
    "sport", "sport_detail", "email", "phone",
    "address_line", "address_city", "address_state", "address_zip",
    "proof_url", "captured_at", "platform", "status",
]


def _q(value: str) -> str:
    return "'" + str(value or "").replace("'", "''") + "'"


def to_csv(records: list[CoachRecord], path: Path | str) -> int:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=CSV_FIELDS)
        w.writeheader()
        for r in records:
            row = r.as_dict()
            row["status"] = gates_hs.status_for(r)
            w.writerow({k: row.get(k, "") for k in CSV_FIELDS})
    return len(records)


def to_sql(records: list[CoachRecord], path: Path | str, source: str) -> int:
    """INSERT new contacts; UPDATE only NULL title/proof_url on existing ones."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "-- High-school coach import. Generated by tools/hs-scraper.",
        "-- Inserts new contacts and enriches existing ones. Never overwrites.",
        "",
    ]
    for r in records:
        status = gates_hs.status_for(r)
        lines.append(
            "INSERT INTO coach_contacts "
            "(email, coach_name, school, sport, level, state, title, phone, "
            "address_line, address_city, address_state, address_zip, "
            "proof_url, captured_at, source, status) VALUES ("
            f"{_q(r.email)}, {_q(r.name)}, {_q(r.school)}, {_q(r.sport)}, 'hs', "
            f"{_q(r.state)}, {_q(r.title)}, {_q(r.phone)}, "
            f"{_q(r.address_line)}, {_q(r.address_city)}, {_q(r.address_state)}, "
            f"{_q(r.address_zip)}, {_q(r.proof_url)}, {_q(r.captured_at)}, "
            f"{_q(source)}, {_q(status)}) ON CONFLICT (email) DO NOTHING;"
        )
        # Enrichment: fill only what is missing, never change status or source.
        lines.append(
            "UPDATE coach_contacts SET "
            f"title = COALESCE(title, {_q(r.title)}), "
            f"proof_url = COALESCE(proof_url, {_q(r.proof_url)}) "
            f"WHERE lower(email) = lower({_q(r.email)}) "
            "AND (title IS NULL OR proof_url IS NULL);"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(records)
